version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:18.19.0
  debian-node-flatpak:
    machine: true
    resource_class: tabinol/debian-node-flatpak

jobs:
  build:
    executor: node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Generate Builds
          command: yarn build
      - run:
          name: Generate Tests
          command: npx jest --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/
            JEST_JUNIT_ADD_FILE_ATTRIBUTE: "true"
      - store_test_results:
          path: ./reports/
  dist:
    executor: debian-node-flatpak
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Generate Artifacts
          command: yarn dist
      - run:
          name: Copy Artifacts
          command: |
            mkdir -p artifacts
            cp dist/*.AppImage dist/*.tar.gz artifacts/
      - run:
          name: Generate Flatpak Artifacts
          command: |
            cd flatpak
            ./flatpak-dist.sh
      - run:
          name: Copy Flatpak Artifacts
          command: |
            mkdir -p artifacts
            cp dist/*.flatpak artifacts/
      - store_artifacts:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: main
          path: artifacts

workflows:
  build-test-dist:
    jobs:
      - build
      - dist:
          context:
            - tabinol-github
          requires:
            - build
